### PR TITLE
fix: remove incorrect max-validity constraint on lifetime input

### LINKED ISSUE #26: BUG: value should be lesser or equal to 31536000
This is simply not true.

Image

### PR DESCRIPTION
**Pull request by lidel**
- closes #26  (cc @2color @Verity-Freedom)

changes:

- components/ipns-inspector.tsx: remove MAX_VALIDITY (was 1 year in seconds) used as max on a milliseconds input, causing browser validation error even for the "1 day" preset
- lib/ipns-machine.tsx: fix misleading comment ("in seconds" -> "in milliseconds")

### CODE REVIEW

File: components/ipns-inspector.tsx [hunk 1]
```diff
@@ -23,7 +23,6 @@ import {
   DialogTrigger,
 } from './ui/dialog'
 
-const MAX_VALIDITY = 365 * 24 * 60 * 60 // 1 year in seconds
```
Comment (lidel) [inline components/ipns-inspector.tsx:26]: ℹ️  afaik there is no 1y limit in specs, we should allow people to create records that are valid for 50  years if they wish, for testing purposes (we have such records in gateway-conformance)

**Comment by Chara-Freedom** [comment]
👍
